site_name: Python Cloudscale.ch
repo_url: https://github.com/cloudscale-ch/python-cloudscale
nav:
    - Home: index.md
    - CLI: cli.md
    - Library: library.md
theme: material
markdown_extensions:
  - codehilite
